inherit_from: .rubocop_todo.yml

# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    # Exclude old db/migrations from new styling to prevent unintentional changes
    - "db/migrate/20*"
    - "vendor/**/*"
    - "bin/**/*"

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "db/schema.rb"

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
